ALTER TABLE DEVELOPERS
  ADD COLUMN SALARY INT;

UPDATE DEVELOPERS
SET SALARY = 2500
WHERE DEVELOPER_ID = 1;
UPDATE DEVELOPERS
SET SALARY = 1800
WHERE DEVELOPER_ID = 2;
UPDATE DEVELOPERS
SET SALARY = 7000
WHERE DEVELOPER_ID = 3;
UPDATE DEVELOPERS
SET SALARY = 3500
WHERE DEVELOPER_ID = 4;
UPDATE DEVELOPERS
SET SALARY = 4200
WHERE DEVELOPER_ID = 5;
UPDATE DEVELOPERS
SET SALARY = 5500
WHERE DEVELOPER_ID = 6;
UPDATE DEVELOPERS
SET SALARY = 4500
WHERE DEVELOPER_ID = 7;