SELECT
  PROJECTS.PROJECT_NAME  AS MOST_EXPENSIVE_PROJECT,
  SUM(DEVELOPERS.SALARY) AS PROJECT_COST
FROM PROJECTS
  JOIN DEVELOPER_PROJECT ON DEVELOPER_PROJECT.PROJECT_ID = PROJECTS.PROJECT_ID
  JOIN DEVELOPERS ON DEVELOPERS.DEVELOPER_ID = DEVELOPER_PROJECT.DEVELOPER_ID
GROUP BY PROJECTS.PROJECT_ID
HAVING SUM(DEVELOPERS.SALARY) > ALL (SELECT DEVELOPERS.SALARY FROM DEVELOPERS);