SELECT SUM(DEVELOPERS.SALARY) AS JAVA_DEVELOPERS_SALARY
FROM SKILLS
  JOIN DEVELOPER_SKILL ON DEVELOPER_SKILL.SKILL_ID = SKILLS.SKILL_ID
  JOIN DEVELOPERS ON DEVELOPERS.DEVELOPER_ID = DEVELOPER_SKILL.DEVELOPER_ID
WHERE SKILLS.SKILL LIKE ('%java%');