INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('Cyklum');
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('SoftServe');
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('EPAM');
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('Luxoft');
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('GlobalLogic');

INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Oleg', 'Melnikov', 1);
INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Mykhailo', 'Sirenko', 2);
INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Iryna', 'Merkulova', 3);
INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Igor', 'Tymoshenko', 4);
INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Volodymyr', 'Solovjov', 5);
INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Max', 'Egorov', 3);
INSERT INTO DEVELOPERS (DEV_NAME, DEV_SURNAME, COMPANY) VALUES
  ('Andriy', 'Kramarenko', 1);

INSERT INTO SKILLS (SKILL) VALUES ('C');
INSERT INTO SKILLS (SKILL) VALUES ('JavaEE');
INSERT INTO SKILLS (SKILL) VALUES ('C++');
INSERT INTO SKILLS (SKILL) VALUES ('Fortran');
INSERT INTO SKILLS (SKILL) VALUES ('C#');
INSERT INTO SKILLS (SKILL) VALUES ('PHP');

INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (1, 1);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (1, 3);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (2, 4);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (2, 3);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (2, 1);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (3, 5);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (3, 1);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (4, 5);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (4, 6);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (5, 2);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (5, 3);
INSERT INTO DEVELOPER_SKILL (DEVELOPER_ID, SKILL_ID) VALUES (6, 6);

INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('Medsevice');
INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('WOT');
INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('GameMax');
INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('Scorpio Studio');
INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('Nova Service');

INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('MetaPlugin');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('Authentication Module');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('Official WebSite Development');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('HR department module');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('Access control system');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('Surveillance Soft Upgrade');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('Motion Detection Plugin');
INSERT INTO PROJECTS (PROJECT_NAME) VALUES ('Temperature lab control system');

INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (1, 7);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (1, 8);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (2, 1);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (2, 3);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (2, 4);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (3, 2);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (4, 5);
INSERT INTO CUSTOMER_PROJECT (CUSTOMER_ID, PROJECT_ID) VALUES (5, 6);

INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (1, 1);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (1, 2);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (2, 4);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (3, 3);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (4, 8);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (4, 6);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (5, 7);
INSERT INTO COMPANY_PROJECT (COMPANY_ID, PROJECT_ID) VALUES (4, 5);

INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (1, 1);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (1, 2);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (7, 2);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (2, 4);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (3, 3);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (4, 6);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (4, 5);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (4, 8);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (5, 7);
INSERT INTO DEVELOPER_PROJECT (DEVELOPER_ID, PROJECT_ID) VALUES (6, 3);